# Themis milter config

# unix:/var/run/pythonfilter  # a named pipe
# local:/var/run/pythonfilter # a named pipe
# inet:8800 # listen on ANY interface
# inet:7871@publichost # listen on a specific interface
# inet6:8020
# inet6:8020@[2001:db8:1234::1] # listen on specific IP
milter_socket : inet:8440
redis_server : localhost
redis_password: 
queue_maxsize : 4
---
global_namespace: AI
# Hours
global_ttl: 86400
policiesByServerPoolFeature: true
featuresByServerPool : false
fallbackToNonPoolPolicies: false

# it will start processing milter action if the spf result is: None, null, softfail, fail or neutral
spfStrictRejectFeature : false

# [ [requests, seconds], [...], ...]
global_conditions : [ [720, 500] ]
global_custom_block : 0
---
# Logging config
logger:
  version: 1
  disable_existing_loggers: false
  formatters:
    simple:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: simple
      stream: ext://sys.stdout
    prod_file_handler:
      class: logging.handlers.RotatingFileHandler
      formatter: simple
      filename: /var/log/themis/themisd.log
      maxBytes: 200000000 # 200MB
      backupCount: 5
      encoding: utf8
  # Console Logging
  #loggers:
  #  __main__:
  #    level: INFO
  #    handlers: [console]
  root:
    level: INFO
    handlers: [prod_file_handler]
