themisweb:  
  build: ./themis
  volumes:
    - ./:/opt/themisweb
  ports:
    - "8080:8080"
  links:
    - redishost
  environment:
    - NODE_ENV=dev
    - TZ=America/Sao_Paulo
    - PYTHONPATH=/opt/themisweb
redishost:
  image: redis
  ports:
    - "6379:6379"
